EquityMaven.Umbraco.TestSite/Models/FullValuationViewModel.cs
using EquityMaven.Umb.TestSite.Models;
using System.Collections.Generic;
using EquityMaven.Data;
using System;
using Umbraco.Forms.Mvc.Models;
using EquityMaven.Data.HelperEntities;
using EquityMaven.Repository;
using System.Linq;
using EquityMaven.Data.Entities;

namespace EquityMaven.Umb.TestSite.Models
{
    public class FullValuationViewModel
    {

        public static FullValuationViewModel GetFullValuationViewModel(int memberId)
        {
            var DataManager = EntityDataManagerService.DataManager;
            var client = DataManager.GetClientByMemberId(memberId);
            PrelimEvaluation preval = null;
            if (client != null)
            {
                preval = DataManager.GetPrelimEvaluations(false).Where(o => o.Email == client.Email).OrderByDescending(o => o.Created).FirstOrDefault();
            }

            var result = new FullValuationViewModel
            {
                ClientId = client?.Id ?? 0,
                MemberId = memberId,
                CompanyName = preval?.CompanyName,
                ISOCurrencySymbol = preval?.ISOCurrencySymbol,
                CurrentCashOnHand = preval?.CurrentCashOnHand ?? 0,
                CurrentInterestBearingDebt = preval?.CurrentInterestBearingDebt ?? 0,
                TRBC2012HierarchicalID = preval?.TRBC2012HierarchicalID,
                IncomeStatement_Revenue = preval?.IncomeStatement_Revenue ?? 0,
                IncomeStatement_CostOfGoodsSold = preval?.IncomeStatement_CostOfGoodsSold ?? 0,
                IncomeStatement_OperatingExpense = preval?.IncomeStatement_OperatingExpense ?? 0
            };
            result.Currencies = DataManager.GetCurrencies().ToList();
            result.Countries = DataManager.GetCountries().ToList();
            return result;
        }

        public int MemberId { get; set; }
        public Int64 ClientId { get; set; }
        public string CompanyName { get; set; }
        public IEnumerable<Currency> Currencies { get; set; }
        public string ISOCurrencySymbol { get; set; }
        public IEnumerable<Country> Countries { get; set; }
        public Guid? SelectedCountryId { get; set; }
        public decimal CurrentCashOnHand { get; set; }
        public decimal CurrentInterestBearingDebt { get; set; }
        public string TRBC2012HierarchicalID { get; set; }
        public decimal IncomeStatement_Revenue { get; set; }
        public decimal IncomeStatement_CostOfGoodsSold { get; set; }
        public decimal IncomeStatement_OperatingExpense { get; set; }
    }
}

EquityMaven.Umbraco.TestSite/Controllers/MemberController.cs
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;
using EquityMaven.Umb.TestSite.Models;

namespace EquityMaven.Umb.TestSite.Controllers
{
    public class MemberController : SurfaceController
    {

        public MemberController()
        {
            //Umbraco.Core.Services.MemberService
        }


        public ActionResult RenderLogin()
        {
            return PartialView("_Login", new LoginModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitLogin(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(model.Username, model.Password))
                {
                    FormsAuthentication.SetAuthCookie(model.Username, false);
                    UrlHelper myHelper = new UrlHelper(HttpContext.Request.RequestContext);
                    if (myHelper.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return Redirect("/login/");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "The username or password provided is incorrect.");
                }
            }
            return CurrentUmbracoPage();
        }

        public ActionResult RenderLogout()
        {
            
            return PartialView("_Logout", null);
        }

        public ActionResult SubmitLogout()
        {
            TempData.Clear();
            Session.Clear();
            FormsAuthentication.SignOut();
            return Redirect("/");
        }



    }
}

EquityMaven.Umbraco.TestSite/Controllers/RegisterController.cs
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;
using EquityMaven.Umb.TestSite.Models;
using System.Linq;
using EquityMaven.Data.Entities;
using System;
using Umbraco.Web.Models;
using umbraco.cms.businesslogic.member;
using EquityMaven.Umb.TestSite.Constants;

namespace EquityMaven.Umb.TestSite.Controllers
{
    public class RegisterController : ApiDbSurfaceController
    {

        
        public RegisterController()
        {
            

        }


        public ActionResult Register(RegisterModel registerModel)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();
            var test = Request.Url.ToString();

            MembershipCreateStatus status;
            registerModel.MemberTypeAlias = EMGeneral.DEFAULTMEMBERTYPEALIAS;
            var member = Members.RegisterMember(registerModel, out status, true);
            if (status == MembershipCreateStatus.Success)
            {
                var existingPreval = DataManager.GetPrelimEvaluation().Where(o => o.Email.ToLower() == member.Email).OrderByDescending(o => o.Created).FirstOrDefault();
                var client = DataManager.GetClientByEmail(registerModel.Email);
                if (client == null)
                {
                    client = new Client { CompanyName = existingPreval?.CompanyName, Email = member.Email, MemberId = 0 };
                    DataManager.SaveClient(client);
                }
                if (existingPreval != null)
                {
                    var clientProfile = new ClientProfile (client, existingPreval);
                    DataManager.SaveClientProfiles(clientProfile);
                }

                return Redirect("/");

            }
            else return CurrentUmbracoPage();

        }
    }
}

EquityMaven.Umbraco.TestSite/Views/FullValuation.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.FullValuation>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
	var backgroundImage = Model.Content.HeroBackgroundImage != null ? Model.Content.HeroBackgroundImage.Url : String.Empty;
}
@*<script src="~/Umbraco/lib/angular/1.1.5/angular.min.js"></script>*@
 <section class="section section--full-height background-image-full overlay overlay--dark section--content-center section--thick-border"
         style="background-image: url('@backgroundImage')">
    <div class="section__hero-content">
        @*@if(Model.Content.FormTheme != null)
        {
        @Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid=Model.Content.ValuationForm, FormTheme=Model.Content.FormTheme, includeScripts = true, mode = "forms" })
        }
        else
        {
        @Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid=Model.Content.ValuationForm, includeScripts = true, mode = "forms" })
        }

 @Umbraco.RenderMacro("RenderUmbracoFormScripts")*@

        @*@Html.Partial("Valuation/FullValuation")*@
        @Html.Partial("Valuation/ValuationIncomeStatement")
        

    </div>
</section>
 

EquityMaven.Umbraco.TestSite/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Home>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
	var backgroundImage = Model.Content.HeroBackgroundImage != null ? Model.Content.HeroBackgroundImage.Url : String.Empty;
}
<section class="section section--full-height background-image-full overlay overlay--dark section--content-center section--thick-border"
         style="background-image: url('@backgroundImage')">
    <div class="section__hero-content">
        <h1>@Model.Content.HeroHeader</h1>
        <p class="section__description">@Model.Content.HeroDescription</p>
        <a class="button button--border--solid" href="@Model.Content.HeroCtalink.Url">
            @Model.Content.HeroCtacaption
        </a>
@if(Model.Content.ValuationForm != null && Model.Content.FormTheme != null)
{
  @Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid=Model.Content.ValuationForm, FormTheme=Model.Content.FormTheme, includeScripts = true, mode = "forms" })
 @Umbraco.RenderMacro("RenderUmbracoFormScripts")
}

    </div>
</section>

<section class="section section">
    @Html.GetGridHtml(Model.Content, "bodyText", "bootstrap3-fluid")
</section>


<section class="section section--themed">

    <div class="container">
        <div class="row">

            <div class="ta-center">
                <h2>@Model.Content.FooterHeader</h2>
                <p class="section__description mw-640 ma-h-auto">@Model.Content.FooterDescription</p>

                <a class="button button--border--light_solid" href="@Model.Content.FooterCtalink.Url">
                    @Model.Content.FooterCtacaption
                </a>

            </div>

        </div>
    </div>

</section>

EquityMaven.Umbraco.TestSite/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
	var backgroundImage = Model.Content.HeroBackgroundImage != null ? Model.Content.HeroBackgroundImage.Url : String.Empty;
}




 <section class="section section--full-height background-image-full overlay overlay--dark section--content-center section--thick-border"
         style="background-image: url('@backgroundImage')"
         >
    <div class="section__hero-content">
      @{ Html.RenderAction("RenderLogin", "Member"); }

    </div>
</section>

EquityMaven.Umbraco.TestSite/Views/Logout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Logout>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
	var backgroundImage = Model.Content.HeroBackgroundImage != null ? Model.Content.HeroBackgroundImage.Url : String.Empty;
}




 <section class="section section--full-height background-image-full overlay overlay--dark section--content-center section--thick-border"
         style="background-image: url('@backgroundImage')"
         >
    <div class="section__hero-content">
     @{ Html.RenderAction("RenderLogout", "Member"); }

    </div>
</section>

 

EquityMaven.Umbraco.TestSite/Views/Master.cshtml
@using ContentModels = Umbraco.Web.PublishedContentModels;
@using Umbraco.Core
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;

    // Get basic design settings from the homepage
    ContentModels.Home home = Model.Content.Site() as ContentModels.Home;
    var colorTheme = Umbraco.GetPreValueAsString(home.ColorTheme);
    var font = Umbraco.GetPreValueAsString(home.Font);
}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title>@Model.Content.Name - @home.Sitename</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" href="@Url.Content("~/css/umbraco-starterkit-style.css")" />
    @RenderSection("Header", required: false)
    
    @{ Html.RenderPartial("head"); }
    <script src="~/scripts/jquery-2.0.2.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>

</head>

<body class="frontpage theme-font-@font theme-color-@colorTheme">
    <div class="mobile-nav">
        <nav class="nav-bar">
            @Html.Partial("~/views/partials/navigation/topNavigation.cshtml")
        </nav>
    </div>

    <header class="header">

        <div class="logo">
            @if (home.SiteLogo != null && !string.IsNullOrEmpty(home.SiteLogo.Url))
            {
                <div class="nav-link--home">
                    <img class="logo-image" src="@home.SiteLogo.Url" alt="@home.Sitename">
                </div>
            }
            else
            {
                <a class="nav-link nav-link--home nav-link--home__text logo-text" href="/">@home.Sitename</a>
            }
        </div>

        <nav class="nav-bar top-nav">
            @Html.Partial("~/Views/Partials/Navigation/TopNavigation.cshtml")
        </nav>

        <div class="mobile-nav-handler">
            <div class="hamburger lines" id="toggle-nav">
                <span></span>
            </div>
        </div>

    </header>

    <main>
        @RenderBody()
    </main>

    <footer class="section--themed">
        <div class="container">
            <div class="row">
                <div class="col-md-12 ta-center">
                    @home.FooterAddress
                </div>
            </div>
        </div>
    </footer>
 
    <script type="text/javascript">
    $(document).ready(function () {
        $(function () {

            $('.datepicker input').datepicker({
                autoclose: true,
                format: 'dd-MM-yyyy'
            });

            $('.datepicker input').on('show', function (e) {
                console.debug('show', e.date, $(this).data('stickyDate'));

                if (e.date) {
                    $(this).data('stickyDate', e.date);
                }
                else {
                    $(this).data('stickyDate', null);
                }
            });

            $('.datepicker input').on('hide', function (e) {
                console.debug('hide', e.date, $(this).data('stickyDate'));
                var stickyDate = $(this).data('stickyDate');

                if (!e.date && stickyDate) {
                    console.debug('restore stickyDate', stickyDate);
                    $(this).datepicker('setDate', stickyDate);
                    $(this).data('stickyDate', null);
                }
            });
        })
    });
    </script>

</body>


</html>




 


 

EquityMaven.Umbraco.TestSite/Views/PreValuation.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.PreValuation>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
	var backgroundImage = Model.Content.HeroBackgroundImage != null ? Model.Content.HeroBackgroundImage.Url : String.Empty;
}
@*<script src="~/Umbraco/lib/angular/1.1.5/angular.min.js"></script>*@
 <section class="section section--full-height background-image-full overlay overlay--dark section--content-center section--thick-border"
         style="background-image: url('@backgroundImage')">
    <div class="section__hero-content">
        @*@if(Model.Content.FormTheme != null)
        {
        @Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid=Model.Content.ValuationForm, FormTheme=Model.Content.FormTheme, includeScripts = true, mode = "forms" })
        }
        else
        {
        @Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid=Model.Content.ValuationForm, includeScripts = true, mode = "forms" })
        }

 @Umbraco.RenderMacro("RenderUmbracoFormScripts")*@

     @Html.Partial("Valuation/PreValuation")
    

    </div>
</section>
 

EquityMaven.Umbraco.TestSite/Views/Register.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Register>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
    var home = Model.Content.Site() as ContentModels.Home;
    //Model.Content.HeroBackgroundImage != null ? Model.Content.HeroBackgroundImage.Url : 
    var backgroundImage = home.HeroBackgroundImage != null ? home.HeroBackgroundImage.Url : String.Empty;
}

 <section class="section section--full-height background-image-full overlay overlay--dark section--content-center section--thick-border"
         style="background-image: url('@backgroundImage')">
    
       @Html.Partial("Membership/Register")

 
</section>
 

EquityMaven.Umbraco.TestSite/Views/ValuationBase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ValuationBase>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
	var backgroundImage = Model.Content.HeroBackgroundImage != null ? Model.Content.HeroBackgroundImage.Url : String.Empty;
}
@*<script src="~/Umbraco/lib/angular/1.1.5/angular.min.js"></script>*@
 <section class="section section--full-height background-image-full overlay overlay--dark section--content-center section--thick-border"
         style="background-image: url('@backgroundImage')">
    <div class="section__hero-content">
        @if(Model.Content.FormTheme != null)
        {
        @Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid=Model.Content.ValuationForm, FormTheme=Model.Content.FormTheme, includeScripts = true, mode = "forms" })
        }
        else
        {
        @Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid=Model.Content.ValuationForm, includeScripts = true, mode = "forms" })
        }

 @Umbraco.RenderMacro("RenderUmbracoFormScripts")

    </div>
</section>
 

EquityMaven.Umbraco.TestSite/Views/ValuationReport.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ValuationReport>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
    var user = Membership.GetUser();
    int memberId = user != null ? Convert.ToInt32(user.ProviderUserKey) : 0;
    var valuationReportId = Request["ValuationReportId"].As<int>();
    var valuation = EquityMaven.Repository.EntityDataManagerService.DataManager.GetFullValuationReport(memberId, valuationReportId);
}

<link href="~/css/valuation-report-style.css" rel="stylesheet" />

<script src="https://d3js.org/d3.v4.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
<script>

    var imageDataTick = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAABGdBTUEAALGPC/xhBQAAACBjSFJN AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAACBFBMVEX///////////////// //79/vz///7////+//7///7////////////+/vzy+ejA4I/3+/H////+/v3y+Oek0l53vA6r1mr+ /v3////////////////9/vzy+eiczk99vxmBwB+/347+//3+//7+//7///7+//7////////////9 /vzr9dyXy0Z+vxuDwSLG4pn///7///7+//3////////////+/vzp9NeUykJ+vxuCwSLL5aP+/v3/ //7///6+342323////7///7+//7////9/vzl8tGQyDp+vxqFwibQ6Kz+/vz///7O56h7vRR+vxu9 3on+/v3///7////+/vzh8MmMxjN/vxyHwyrT6bH9/vz///72+++s1mx+vxqBwB/B4JL+//39/vvb 7cCLxTF+vxuHxCra7L3+/vz////////6/PWk0l59vxmBwCDB4JLW67eIxCt+vxuLxjHd7sL9/vz/ ///////+/v32+/Cj0V19vxmAwB7E4pfS6bCFwiZ/vxuMxjPh8Mn+/v3////+//31+u6j0Vx9vxmF wyeFwiZ+vxuQyDrl8tH9/vz////////+/v33+/Cfz1V+vxuBwB+SyT7n89X9/vz////+/v3x+Oea zUyWy0Ts9t79/vz+/v3x+Obx+Ob+/v3+//7////////+//3////////+//7+//4dph5rAAAAAWJL R0QAiAUdSAAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAAd0SU1FB+IFDwgoGTD+2N0AAAEMSURBVBjT fZDTcoMBFAa3tv3XTmrbtm3btm3bTNuXbCbtZJpcdC/34nxnFpRRUVU2aqhraCo5LbR10NVTcPoY YGhkrOBMMMXM3MLSCqxtEGTOFjvsHRydnF1wdXP3wBNEgtgLbx9fP38CCISgYEQhhIYRHhEZFU1M LHHxCYlJyQgpqaSlZ2RmkZ0DuXn5BRQWFZdQWlZeUUlVtfR4TW1dfQONTTS3tLa109FJl3S0u6e3 rx8GBoeGRxgdY1zqJpicmp6ZnZtfWFxieeX3vVXW1jc2t7Z3dtnb56fGAYccHZ+cnp1zcUmIPMwV 1ze3d9yLBdGfXA88PvEsm5Djycvr2zsSQSHPB59fSPifb/BLPAuqxI+3AAAAJXRFWHRkYXRlOmNy ZWF0ZQAyMDE4LTA1LTE1VDA4OjQwOjI1LTA3OjAwsQaxsQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAx OC0wNS0xNVQwODo0MDoyNS0wNzowMMBbCQ0AAAAASUVORK5CYII=";
    var imageDataCross = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAABGdBTUEAALGPC/xhBQAAACBjSFJN AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAACQFBMVEX//////////v7//Pz/ /////////////v7//f3//////////v7//v7//////v7//////v7//f3//v7/////8vL/1NT//Pz/ /////////f3/5+f/2tr//v7//v7/9fX/Wlr/DAz/wcH//Pz//////v7//v7/+Pj/SEj/FRX/x8f/ /v7//////Pz/ysr/DQ3/AAD/ExP/v7//+/v//Pz/9PT/Tk7/Zmb//f3//////f3/tLT/Cgr/EhL/ wMD/+/v/9/f/TEz/UVH/9vb//v7//////f3/sbH/DAz/ExP/vb3/8fH/Tk7/UlL/9PT//v7///// +/v/s7P/Cgr/ExP/ubn/VFT/T0//9vb//f3//Pz/sLD/Cwv/BAT/AgL/T0//9PT//f3/////+vr/ p6f/BQX/QkL/+/v//v7//f3//////Pz/8/P/VVX/AgL/GRn/wsL/+/v/9/f/TEz/RUX/Fhb/EhL/ wMD/////9PT/Tk7/YGD/s7P/Cwv/ExP/+/v/////9/f/TU3/X1///f3//Pz/s7P/Cgr/EhL/wMD/ /f3//////v7/6+v/S0v/YmL/+vr//f3//Pz/sbH/DAz/FBT/tbX//v7//////Pz/xcX/Cgr/YGD/ /f3//v7//v7/////s7P/Cwv/a2v//f3//////f3/qan/Zmb/+fn//f3//Pz/p6f/Z2f//Pz///// /////v7//v7//f3//////////////f3//v7//v7//////v7//f3//v7///////////9AWfnRAAAA AWJLR0QAiAUdSAAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAAd0SU1FB+IFDwgtMA87tPQAAAFuSURB VBjTLY/5W8xxFIXfmIkZaTDUUEhJpTiSLCVpEaFNWUrZlzZEKOuUJS2kIvtWIVsoSyrlX+vzncf9 6T7vPc8954AfU6Zis2PGn2nTcTgxbEbAzEAXZrUxa7ZrjiHgZu48goKxe5jPghBCPbCQRYvDlhAe 4WRp5LKo6BiWxxLHipVaFc9qEliTKK1l3XqCN5CUrI0pbApI3SylpZNhfmZuIWurtmWzfYe0M4dc 7DjIy6dglwqLdkt79rLP5+7EXUzJfpWW6cBBDvkYRnv4CEd1TMdPnCynwsfwUElVtU7p9BlqTF6L 2Uy+s+ek2vO6cNHktbrVGV39JekyV67qWjzXvZY2koZG6cbNW9xu0p1mWlqhjbv3pPb7dHTS9UAP u3n0mCc8fabnL16+4nU+b3rUS99beMf7/g98NPncn/j8ZYCvxt3vm43vg3itbkM/+PnL2Nu9/B7+ Y5jVbWR07K85WjMe+n9xMPHPCjQJ6RpSGYmaWLYAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTgtMDUt MTVUMDg6NDU6NDgtMDc6MDDwlxKyAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE4LTA1LTE1VDA4OjQ1 OjQ4LTA3OjAwgcqqDgAAAABJRU5ErkJggg==";

</script>
<section class="section">

    <div class="section__hero-content">



        @{
            for (var i = 1; i <= 34; i++)
            {


                var pageNumber = ("000" + i.ToString());
                pageNumber = pageNumber.Substring(pageNumber.Length - 2, 2);
 
                var FullValuationPageModel = new EquityMaven.Umb.TestSite.Models.FullValuationPageModel { Page = i, TotalPages = 34, FullValuationReport = valuation };
                <page size="A4" layout="landscape">
                    @Html.Partial("Valuation/Report/Page" + pageNumber, FullValuationPageModel)
                </page>
              
                <div style="page-break-after: always;"></div>
            }
        }

    </div>
</section>
 

EquityMaven.Umbraco.TestSite/Views/ValuationReportPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ValuationReportPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}